;;;; An actual subprocess DAP adapter used by the executable boundary tests.
(require :asdf)
(let ((*standard-output* *error-output*)
      (*trace-output* *error-output*))
  (load (second sb-ext:*posix-argv*))
  (asdf:load-asd (third sb-ext:*posix-argv*))
  (asdf:load-system "daphne"))

(in-package #:daphne)
(let ((input (sb-sys:make-fd-stream 0 :input t :element-type '(unsigned-byte 8) :buffering :none))
      (output (sb-sys:make-fd-stream 1 :output t :element-type '(unsigned-byte 8) :buffering :none))
      (seq 0) (launch nil) (held nil))
  (labels ((send (value)
             (setf (gethash "seq" value) (incf seq))
             (write-frame output value))
           (event (name &optional (body (json-object)))
             (send (json-object "type" "event" "event" name "body" body)))
           (respond (request &optional (body (json-object)) (success t))
             (send (json-object "type" "response" "request_seq" (json-get request "seq")
                                "command" (json-get request "command") "success" (json-boolean success)
                                "body" body "message" (if success "" "fixture failure")))))
    ;; More than a pipe buffer, testing the independent stderr drainer.
    (dotimes (index 100000) (write-char #\x *error-output*))
    (finish-output *error-output*)
    (loop for request = (read-frame input) while request
          for command = (json-get request "command")
          do (cond
               ((equal (json-get request "type") "response") nil)
               ((equal command "initialize")
                (respond request (json-object "supportsConfigurationDoneRequest" t)))
               ((member command '("launch" "attach") :test #'equal)
                (setf launch request) (event "initialized"))
               ((equal command "configurationDone")
                (respond request) (event "stopped" (json-object "threadId" 1 "reason" "entry"))
                (respond launch))
               ((equal command "setBreakpoints")
                (respond request (json-object "breakpoints" (vector (json-object "verified" t "line" 3)))))
               ((equal command "threads")
                (respond request (json-object "threads" (vector (json-object "id" 1 "name" "main")))))
               ((equal command "stackTrace")
                (respond request (json-object "stackFrames" (vector (json-object "id" 2 "name" "entry" "line" 3 "column" 1))
                                              "totalFrames" 1)))
               ((equal command "scopes")
                (respond request (json-object "scopes" (vector (json-object "name" "locals" "variablesReference" 4 "expensive" (json-boolean nil))))))
               ((equal command "variables")
                (respond request (json-object "variables" (vector (json-object "name" "answer" "value" "42" "variablesReference" 0)))))
               ((equal command "evaluate")
                (respond request (json-object "result" "λ:42" "variablesReference" 0)))
               ((equal command "continue") (event "continued") (respond request (json-object "allThreadsContinued" t)))
               ((member command '("pause" "stepIn" "next" "stepOut") :test #'equal)
                (event "stopped") (respond request))
               ((member command '("terminate" "disconnect") :test #'equal)
                (respond request) (event "terminated"))
               ((equal command "reject") (respond request (json-object) nil))
               ((equal command "echo") (respond request (json-get request "arguments")))
               ((equal command "duplicate") (respond request) (respond request))
               ((equal command "stop-reading") (respond request) (sleep 1000))
               ((equal command "events")
                (event "output" (json-object "ordinal" 1))
                (event "custom" (json-object "ordinal" 2))
                (event "output" (json-object "ordinal" 3)) (respond request))
               ((equal command "fragmented")
                (let* ((body (json-encode-utf8
                              (json-object "seq" (incf seq) "type" "response" "request_seq" (json-get request "seq")
                                           "command" command "success" t "body" (json-object "text" "λ😀"))))
                       (header (babel:string-to-octets
                                (format nil "Content-Length: ~D~C~C~C~C" (length body)
                                        #\Return #\Newline #\Return #\Newline) :encoding :ascii)))
                  (loop for byte across (concatenate '(vector (unsigned-byte 8)) header body)
                        do (write-byte byte output) (finish-output output) (sleep 0.001))))
               ((equal command "reorder")
                (if held (progn (respond request (json-get request "arguments"))
                                (respond held (json-get held "arguments")) (setf held nil))
                    (setf held request)))
               ((equal command "hang") nil)
               ((equal command "eof") (return))
               ((equal command "reply-eof") (respond request (json-object "complete" t)) (return))
               ((equal command "bad-frame")
                (write-sequence (babel:string-to-octets "Content-Length: nope" :encoding :ascii) output)
                (write-sequence #(13 10 13 10) output) (finish-output output))
               ((equal command "wrong-correlation")
                (send (json-object "type" "response" "request_seq" 999999 "command" command "success" t)))
               ((equal command "wrong-command")
                (send (json-object "type" "response" "request_seq" (json-get request "seq") "command" "other" "success" t)))
               ((equal command "flood") (dotimes (index 50) (event "output")) (respond request))
               ((equal command "reverse")
                (send (json-object "type" "request" "command" "runInTerminal" "arguments" (json-object)))
                (respond request))
               (t (respond request (json-object) nil))))))
