(in-package #:daphne)

(define-condition dap-error (error)
  ((message :initarg :message :reader dap-error-message)
   (cause :initarg :cause :initform nil :reader dap-error-cause))
  (:report (lambda (condition stream)
             (write-string (dap-error-message condition) stream)))
  (:documentation "A structured DAP failure with an optional underlying cause."))

(define-condition dap-protocol-error (dap-error) ()
  (:documentation "Malformed framing or DAP message."))
(define-condition dap-transport-error (dap-error) ()
  (:documentation "The adapter stream or process failed."))
(define-condition dap-state-error (dap-error) ()
  (:documentation "Operation is invalid for this session state."))
(define-condition dap-limit-error (dap-error) ()
  (:documentation "A configured resource bound was exceeded."))
(define-condition dap-timeout (dap-error) ()
  (:documentation "A bounded operation did not complete before its deadline."))
(define-condition dap-cancelled (dap-error) ()
  (:documentation "The caller cancelled an operation."))
(define-condition dap-request-error (dap-error)
  ((response :initarg :response :reader dap-request-error-response))
  (:documentation "The adapter rejected a request; RESPONSE is the complete response."))

(defun protocol-error (control &rest arguments)
  "Signal a framing or message error."
  (error 'dap-protocol-error :message (apply #'format nil control arguments)))

(defun read-frame (stream &key (max-header 8192) (max-body (* 16 1024 1024)))
  "Read one Content-Length framed JSON object from a binary STREAM.
Return NIL only for clean EOF before the first header byte. Bound both header
and body allocation; reject duplicate lengths, bare LF and truncated frames."
  (let ((header (make-array 0 :element-type 'character :adjustable t :fill-pointer 0))
        (length nil))
    (loop for byte = (read-byte stream nil nil)
          do (unless byte
               (if (zerop (length header)) (return-from read-frame nil)
                   (protocol-error "Truncated DAP header.")))
             (unless (< byte 128) (protocol-error "Non-ASCII DAP header."))
             (when (>= (length header) max-header)
               (error 'dap-limit-error :message "DAP header exceeds its bound."))
             (vector-push-extend (code-char byte) header)
          when (and (>= (length header) 4)
                    (string= header (format nil "~C~C~C~C" #\Return #\Newline #\Return #\Newline)
                             :start1 (- (length header) 4)))
            do (return))
    (loop with start = 0
          for end = (position #\Return header :start start)
          do (unless (and end (< (1+ end) (length header))
                          (char= (char header (1+ end)) #\Newline))
               (protocol-error "DAP headers require CRLF."))
             (let ((line (subseq header start end)))
               (when (zerop (length line)) (return))
               (when (find #\Newline line) (protocol-error "Bare LF in DAP header."))
               (let ((colon (position #\: line)))
                 (unless colon (protocol-error "Malformed DAP header field."))
                 (when (string-equal (subseq line 0 colon) "Content-Length")
                   (when length (protocol-error "Duplicate Content-Length."))
                   (let ((value (string-trim '(#\Space #\Tab) (subseq line (1+ colon)))))
                     (unless (and (plusp (length value)) (every #'digit-char-p value))
                       (protocol-error "Invalid Content-Length."))
                     (setf length (parse-integer value))))))
             (setf start (+ end 2)))
    (unless length (protocol-error "Missing Content-Length."))
    (unless (<= 1 length max-body)
      (error 'dap-limit-error :message "DAP body exceeds its bound or is empty."))
    (let ((body (make-array length :element-type '(unsigned-byte 8))))
      (loop for index below length
            for byte = (read-byte stream nil nil)
            do (unless byte (protocol-error "Truncated DAP body."))
               (setf (aref body index) byte))
      (let ((value (handler-case
                       (json-decode (babel:octets-to-string body :encoding :utf-8 :errorp t))
                     (error (cause)
                       (error 'dap-protocol-error :message "Invalid DAP JSON/UTF-8." :cause cause)))))
        (unless (hash-table-p value) (protocol-error "DAP body must be an object."))
        value))))

(defun write-frame (stream message &key (max-body (* 16 1024 1024)))
  "Write one JSON MESSAGE using UTF-8 byte length, then flush binary STREAM."
  (let ((body (json-encode-utf8 message)))
    (when (> (length body) max-body)
      (error 'dap-limit-error :message "Outgoing DAP body exceeds its bound."))
    (write-sequence (babel:string-to-octets
                     (format nil "Content-Length: ~D~C~C~C~C" (length body)
                             #\Return #\Newline #\Return #\Newline)
                     :encoding :ascii) stream)
    (write-sequence body stream)
    (finish-output stream))
  message)

(defclass transport () ()
  (:documentation "A blocking message transport owned by one session."))
(defgeneric transport-read (transport)
  (:documentation "Read a message or NIL at EOF; errors abort the session."))
(defgeneric transport-write (transport message)
  (:documentation "Write a message. Session serializes calls."))
(defgeneric transport-close (transport)
  (:documentation "Idempotently close transport and unblock readers/writers."))

(defclass stream-transport (transport)
  ((input :initarg :input :reader transport-input)
   (output :initarg :output :reader transport-output)
   (max-header :initarg :max-header :reader transport-max-header)
   (max-body :initarg :max-body :reader transport-max-body))
  (:documentation "An owned pair of binary streams with framing bounds."))

(defun make-stream-transport (input output &key (max-header 8192) (max-body (* 16 1024 1024)))
  "Construct an owned transport from INPUT (adapter stdout) and OUTPUT (stdin)."
  (make-instance 'stream-transport :input input :output output
                 :max-header max-header :max-body max-body))
(defmethod transport-read ((transport stream-transport))
  (read-frame (transport-input transport) :max-header (transport-max-header transport)
              :max-body (transport-max-body transport)))
(defmethod transport-write ((transport stream-transport) message)
  (write-frame (transport-output transport) message :max-body (transport-max-body transport)))
(defmethod transport-close ((transport stream-transport))
  (ignore-errors (close (transport-input transport) :abort t))
  (ignore-errors (close (transport-output transport) :abort t))
  nil)
