(in-package #:daphne)

(defvar *test-checks* 0)

(defun check (value &optional (message "Daphne assertion failed"))
  "Record one executable assertion."
  (incf *test-checks*)
  (unless value (error "~A" message)))

(defun check-error (type thunk)
  "Assert THUNK signals exactly the requested condition family."
  (let ((condition (handler-case (progn (funcall thunk) nil) (error (value) value))))
    (check (typep condition type) (format nil "Expected ~A, got ~S" type condition))
    condition))

(defun call-with-bytes (bytes function)
  "Call FUNCTION on a temporary binary stream containing BYTES."
  (uiop:with-temporary-file (:stream stream :direction :io :element-type '(unsigned-byte 8))
    (write-sequence bytes stream) (finish-output stream) (file-position stream 0)
    (funcall function stream)))

(defun header-bytes (header &optional (body "{}"))
  "Encode HEADER with explicit CRLF and BODY."
  (babel:string-to-octets (concatenate 'string header (format nil "~C~C~C~C" #\Return #\Newline #\Return #\Newline) body)
                          :encoding :utf-8))

(defun test-framing ()
  "Exercise byte lengths, multiple frames and strict bounded parsing."
  (uiop:with-temporary-file (:stream stream :direction :io :element-type '(unsigned-byte 8))
    (write-frame stream (json-object "text" "λ 😀"))
    (write-frame stream (json-object "second" t))
    (file-position stream 0)
    (check (equal "λ 😀" (json-get (read-frame stream) "text")))
    (check (json-get (read-frame stream) "second"))
    (check (null (read-frame stream))))
  (dolist (bytes (list (header-bytes "Content-Length: nope")
                      (header-bytes "Content-Length: -1")
                      (header-bytes "Other: 2")
                      (header-bytes (format nil "Content-Length: 2~C~CContent-Length: 2" #\Return #\Newline))
                      (header-bytes (format nil "Content-Length: 2~COther: nope" #\Newline))
                      (header-bytes "Content-Length: 4")
                      (header-bytes "Content-Length: 1" "[")
                      (header-bytes "Content-Length: 2" "[]")
                      #(67 111 110)
                      (concatenate '(vector (unsigned-byte 8))
                                   (header-bytes "Content-Length: 1" "") #(255))))
    (call-with-bytes bytes (lambda (stream) (check-error 'dap-protocol-error (lambda () (read-frame stream))))))
  (call-with-bytes (header-bytes "Content-Length: 100000000000")
                  (lambda (stream) (check-error 'dap-limit-error (lambda () (read-frame stream :max-body 16)))))
  (call-with-bytes (header-bytes "Content-Length: 2")
                  (lambda (stream) (check-error 'dap-limit-error (lambda () (read-frame stream :max-header 3)))))
  (uiop:with-temporary-file (:stream stream :direction :io :element-type '(unsigned-byte 8))
    (check-error 'dap-limit-error (lambda () (write-frame stream (json-object "text" "long") :max-body 1)))))

(defun fixture-session (&rest options)
  "Start a fresh actual adapter process with dependencies from test setup."
  (let* ((root (asdf:system-source-directory "daphne"))
         (setup (or (uiop:getenv "DAPHNE_TEST_SETUP")
                    (namestring (merge-pathnames "../../.qlot/setup.lisp" root)))))
    (apply #'start-adapter (namestring sb-ext:*runtime-pathname*)
           (list "--noinform" "--script" (namestring (merge-pathnames "fixture.lisp" root))
                 setup (namestring (merge-pathnames "daphne.asd" root)))
           options)))

(defun test-lifecycle ()
  "Exercise launch and attach, configuration ordering and every semantic operation."
  (dolist (mode '(:launch :attach))
    (multiple-value-bind (session transport) (fixture-session :stderr-limit 128)
      (unwind-protect
           (progn
             (check (eq :new (session-state session)))
             (check (json-get (session-initialize session) "supportsConfigurationDoneRequest"))
             (check (eq :initialized (session-state session)))
             (check-error 'dap-state-error (lambda () (session-initialize session)))
             (let ((configured nil))
               (session-start session mode (json-object "program" "fixture")
                              :configure (lambda (value)
                                           (check (eq session value))
                                           (setf configured t)
                                           (let ((body (session-set-breakpoints value (json-object "path" "/fixture.lisp")
                                                                                (vector (json-object "line" 3)))))
                                             (check (json-get (aref (json-get body "breakpoints") 0) "verified")))))
               (check configured))
             (check (eq :stopped (session-state session)))
             (check (= 128 (length (adapter-stderr transport))))
             (check (= 1 (length (json-get (session-threads session) "threads"))))
             (check (= 1 (json-get (session-stack-trace session 1 :levels 2) "totalFrames")))
             (check (= 4 (json-get (aref (json-get (session-scopes session 2) "scopes") 0) "variablesReference")))
             (check (equal "42" (json-get (aref (json-get (session-variables session 4) "variables") 0) "value")))
             (check (equal "λ:42" (json-get (session-evaluate session "answer" :frame-id 2) "result")))
             (session-continue session 1)
             (check (eq :running (session-state session)))
             (session-pause session 1)
             (check (eq :stopped (session-state session)))
             (dolist (kind '(:in :over :out)) (session-step session 1 kind))
             (session-request session "reverse" (json-object))
             (check (find "continued" (session-events session) :test #'equal
                          :key (lambda (event) (json-get event "event"))))
             (session-terminate session :disconnect (eq mode :attach))
             (check (eq :closed (session-state session)))
             (check (not (sb-ext:process-alive-p (adapter-process transport))))
             (check-error 'dap-state-error (lambda () (session-threads session))))
        (session-close session)
        (session-close session)))))

(defun test-correlation ()
  "Concurrent requests receive out-of-order responses, with no cross-talk."
  (multiple-value-bind (session transport) (fixture-session)
    (declare (ignore transport))
    (unwind-protect
         (let ((first nil) (second nil) (failure nil))
           (let ((thread (bt:make-thread
                          (lambda ()
                            (handler-case
                                (setf first (session-request session "reorder" (json-object "id" 1)))
                              (error (cause) (setf failure cause)))))))
             (setf second (session-request session "reorder" (json-object "id" 2)))
             (bt:join-thread thread)
             (check (null failure))
             (check (= 1 (json-get first "id")))
             (check (= 2 (json-get second "id"))))
           (let ((failure (check-error 'dap-request-error (lambda () (session-request session "reject" (json-object))))))
             (check (equal "reject" (json-get (dap-request-error-response failure) "command"))))
           (check (= 3 (json-get (session-request session "echo" (json-object "id" 3)) "id"))))
      (session-close session))))

(defun test-failures ()
  "Actual process failures and cancellation close and reap the owned adapter."
  (dolist (case '(("bad-frame" dap-protocol-error) ("wrong-correlation" dap-protocol-error)
                  ("wrong-command" dap-protocol-error) ("eof" dap-transport-error)
                  ("hang" dap-timeout)))
    (multiple-value-bind (session transport) (fixture-session)
      (unwind-protect
           (progn
             (session-initialize session)
             (check-error (second case)
                          (lambda () (session-request session (first case) (json-object) :timeout 2)))
             (check (eq :failed (session-state session)))
             (check (not (sb-ext:process-alive-p (adapter-process transport)))))
        (session-close session))))
  (multiple-value-bind (session transport) (fixture-session)
    (session-initialize session)
    (let ((calls 0))
      (check-error 'dap-cancelled
                   (lambda () (session-request session "hang" (json-object)
                                               :cancel-p (lambda () (> (incf calls) 20)))))
      (check (not (sb-ext:process-alive-p (adapter-process transport))))))
  (multiple-value-bind (session transport) (fixture-session :max-events 2)
    (session-initialize session)
    (check-error 'dap-limit-error (lambda () (session-request session "flood" (json-object))))
    (check (not (sb-ext:process-alive-p (adapter-process transport)))))
  (multiple-value-bind (session transport) (fixture-session)
    (session-initialize session)
    (check-error 'dap-timeout (lambda () (session-wait-event session "absent" :timeout 0.1)))
    (check (not (sb-ext:process-alive-p (adapter-process transport)))))
  (check-error 'dap-transport-error (lambda () (start-adapter "/nonexistent/daphne-adapter" nil)))
  (check-error 'dap-limit-error (lambda () (fixture-session :max-pending 0))))

(defun run-tests ()
  "Run framing and actual adapter-process tests; return assertion count."
  (let ((*test-checks* 0))
    (test-framing) (test-lifecycle) (test-correlation) (test-failures)
    (format t "~&Daphne: ~D assertions passed.~%" *test-checks*)
    *test-checks*))
